# Copyright 2020-2021, The Tremor Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Default values for the tremor chart
#

image:
  repository: tremorproject/tremor
  tag: 0.11.4
  pullPolicy: IfNotPresent

kind: "DaemonSet"

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 512Mi

tolerations:
  - effect: NoSchedule
    operator: Exists

serviceAccount:
  create: true
  # if not specified, name defaults to fullname
  name: ""

files:
  config.yaml: |-
    onramp:
      - id: metronome
        type: metronome
        config:
          interval: 10000
    binding:
      - id: default
        links:
          '/onramp/metronome/{instance}/out': [ '/pipeline/main/{instance}/in' ]
          '/pipeline/main/{instance}/out': [ '/offramp/system::stdout/system/in' ]
          '/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
    mapping:
      /binding/default/01:
        instance: '01'
  main.trickle: |-
    select event from in into out

fullnameOverride: ""
nameOverride: ""

affinity: {}
nodeSelector: {}

psp:
  create: true

extraVolumes: {}

extraVolumeMounts: []
extraContainers: []
extraInitContainers: []

hostNetwork: true

updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
  type: RollingUpdate

hostDummyInterface:
  create: false

#priorityClassName: tremor-cluster-critical
replicaCount: 1

strategy: {}

service:
  enabled: false
  name: tremor
  type: ClusterIP
  annotations: {}

